ProjectSWGCore/Holocore

serverdata/spawn/invasion_tusken_vs_jawa.sdb, serverdata/spawn/zones_nobuild_nospawn.sdb
Added datatable for no build / no spawn zones
=> Content update

src/main/java/com/projectswg/holocore/resources/support/data/location/ClosestLocationReducer.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DynamicSpawnLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/NoSpawnZoneLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/TerrainLevelLoader.java, src/main/java/com/projectswg/holocore/services/support/npc/NonPlayerCharacterManager.java, src/main/java/com/projectswg/holocore/services/support/npc/spawn/DynamicSpawnService.java, src/test/java/com/projectswg/holocore/resources/support/data/location/TestClosestLocationReducer.java, src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestDynamicSpawnLoader.java, src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestNoSpawnZoneLoader.java, src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestTerrainLevelLoader.java
There are no NPCs and the eggs may spawn below ground or mid-air.
We need to be able to read terrain height before we can implement above properly.
For now, I think it's good to get this off my fork because of all the dataloaders I wrote that may be used for other features.
Relates to  #150
=> Eggs for dynamic spawns

src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.java, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionManager.java, src/main/java/com/projectswg/holocore/services/gameplay/gcw/CivilWarPointService.java, src/main/java/com/projectswg/holocore/services/gameplay/gcw/CivilWarPvpService.java, src/main/java/com/projectswg/holocore/services/gameplay/gcw/CivilWarRankService.java, src/main/java/com/projectswg/holocore/services/gameplay/gcw/GalacticCivilWarManager.java, src/test/java/com/projectswg/holocore/services/gameplay/gcw/TestCivilWarPvpService.java, src/test/java/com/projectswg/holocore/services/gameplay/gcw/TestCivilWarRankService.java
Relates to #29.
Regions are not yet implemented. Figured I'd get the class split merged first so the changelog doesn't become massive.
=> Split CivilWarService into CivilWarPointService, CivilWarPvpService and CivilWarRankService

src/main/java/com/projectswg/holocore/resources/support/objects/swg/SWGObject.java, src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGObject.java
=> Fix issue where you can only equip one ring

src/main/java/com/projectswg/holocore/services/support/global/zone/LoginService.java
I got this when I was zoning in on my local server with a single character.
```
27-03-20 23:00:17.131 E: Fatal Exception while processing intent: ObjectCreatedIntent
27-03-20 23:00:17.134 E: Exception in thread "intent-processor-9" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
27-03-20 23:00:17.134 E: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
27-03-20 23:00:17.134 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.invoke(Service.java:135)
27-03-20 23:00:17.134 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
27-03-20 23:00:17.134 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManag …
```
=> Fix potential concurrent modifications in LoginService

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffNpcs.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffPlayers.java
=> Prevent players from buffing NPCs #176

src/main/java/com/projectswg/holocore/resources/support/data/server_info/SdbColumnArraySet.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/SdbLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/BuffLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CollectionLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/PerformanceLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/npc/LootTableLoader.kt
=> Fixed issue where buff value was displayed as "1.#R" points #177

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
=> Healing, buffing and attack results displayed correctly in the combat log

src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Implemented Issue #224: "CBT - Ability to spawn inside cells"
=> Added option to teleport into buildings with the teleportTo function

src/main/java/com/projectswg/holocore/intents/gameplay/jedi/TuneCrystalIntent.java, src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java, src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/TuneCrystalRadial.java, src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/ServerAttribute.java, src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.java, src/main/java/com/projectswg/holocore/services/gameplay/jedi/JediManager.java, src/main/java/com/projectswg/holocore/services/gameplay/jedi/LightsaberCrystalService.java, src/test/java/com/projectswg/holocore/resources/support/objects/radial/object/TestTuneCrystalRadial.java
Power crystals cannot be tuned yet.
=> Jedi can tune lightsaber color crystals #191

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt, src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
Color crystals should now be colored.
=> 'item' type items now have generic item attribute applied #243

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
=> AoE heals no longer unnecessarily heal invulnerable NPCs #256

src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt
Should complete implementation of /createNPC for now.
Issue: #37
=> Don't create spawners for NPCs with IDs that do not exist #37

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java
Relates to #65.
It's possible that the combat log entry isn't exactly on point, but the mechanic should work.
=> Added glancing blow combat roll #65

src/main/java/com/projectswg/holocore/services/support/npc/spawn/DynamicSpawnService.java
Fixes #273 
Additionally makes the spawn locations more random.
=> Fixed an issue where dynamic NPCs would spam around players not in God Mode #273

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/chat/CmdSetSpokenLanguage.java, src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/chat/CmdSpatialChatInternal.java, src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java, src/main/java/com/projectswg/holocore/services/support/global/chat/ChatSpatialService.java, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
=> Added racial languages #53

src/main/java/com/projectswg/holocore/services/gameplay/player/guild/GuildService.java
Can be seen with the /examine command. Before it would just say Loading... forever because the server never responded to the request.
We don't have guilds yet, so everyone's just unguilded for now.
=> Guild information for a player no longer loads forever

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/CmdRemoveBuff.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.java, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
Only buffs marked player removable can be removed
=> Add support for removing a buff by right-clicking on it

src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
=> Aggressive NPCs ignore players that have been incapacitated recently #3

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt, src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt, src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/SWGObjectRadial.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
=> Consumed item charges are now set correctly and is supported by splitting/stacking #281

src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java
=> PvP zones are now only applied to the intended planet instead of every planet #290

serverdata/nge/conversation/imperial_recruiter/neutral_root.json, src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/NpcAnimationEvent.java, src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/PlayerAnimationEvent.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/ConversationLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/NpcAnimationEventParser.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/PlayerAnimationEventParser.java
=> Added npc_animation and player_animation events to conversations #303

serverdata/nge/conversation/junk_dealer_generic/accept.json, src/main/java/com/projectswg/holocore/intents/gameplay/junkdealer/JunkDealerIntents.kt, src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/ShowSellableItemsEvent.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/ConversationLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/ShowSellableItemsEventParser.java, src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/ServerAttribute.java, src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.java, src/main/java/com/projectswg/holocore/services/gameplay/junkdealer/JunkDealerService.java
=> Newly looted items with a value are now sellable to junk dealers #307

src/main/java/com/projectswg/holocore/utilities/AddQuestsToCrcDatabase.java
In case we ever want to add new quests we could update the CRC database using this utility.
=> Created utility for adding quest strings to the CRC database and outputting to new .csv file

src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
=> Character Builder Terminal now supports granting level 90

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java, src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandAttack.java
=> Cone of Effect attacks #77

src/main/java/com/projectswg/holocore/resources/support/data/collections/SWGBitSet.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectShared.java, src/test/java/com/projectswg/holocore/resources/support/data/collections/TestSWGBitSet.java
Fixes #326
Unable to test, getting compilation errors in ProjectSWGRunner.
=> Progress in Collections is no longer lost upon server shutdown #326

serverdata/nge/conversation/spawn_conversation_map.msdb, serverdata/nge/conversation/trainers.sdb, serverdata/nge/conversation/trainers/brawler_skills.json, serverdata/nge/conversation/trainers/brawler_start.json, serverdata/nge/spawn/common_tatooine.sdb, src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/ShowAvailableSkillsEvent.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/ConversationLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/ShowAvailableSkillsEventParser.java, src/main/java/com/projectswg/holocore/services/gameplay/training/AvailableSkillsWindow.java, src/main/java/com/projectswg/holocore/services/gameplay/training/Experience.java, src/main/java/com/projectswg/holocore/services/gameplay/training/Profession.java, src/main/java/com/projectswg/holocore/services/gameplay/training/Skill.java, src/main/java/com/projectswg/holocore/services/gameplay/training/SkillRepository.java, src/main/java/com/projectswg/holocore/services/gameplay/training/SkillsSdbSkillRepository.java, src/main/java/com/projectswg/holocore/services/gameplay/training/Trainee.java, src/main/java/com/projectswg/holocore/services/gameplay/training/TraineeImpl.java, src/main/java/com/projectswg/holocore/services/gameplay/training/Training.java, src/test/java/com/projectswg/holocore/services/gameplay/training/TraineeFake.java, src/test/java/com/projectswg/holocore/services/gameplay/training/TrainingTest.java
=> Skill training, with brawler trainer as example

src/main/java/com/projectswg/holocore/services/gameplay/player/badge/BadgeService.java
Fixes #399
The data loading had already been converted,
but the Service didn't use it fully and still
had the old clientdata code
=> Actually use the new badge dataloader that uses sdb instead of the old code that uses iff

src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/ContainerObjectRadial.java
=> Fixed bug with 'Set name' on containers not doing anything #482

src/main/java/com/projectswg/holocore/ProjectSWG.java, src/main/java/com/projectswg/holocore/services/support/global/zone/ZoneService.java
Took a minute, so I figured why not just get it done.
Fixes #479
=> Removed unused versioning #479

src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectClientServerNP.java, src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
We were running too fast and climbing hills too easily.
Values shamelessly copied from swgemu.
**NOTE**: Won't change movement of existing characters.
=> Changed movement to Pre-NGE variant

src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.java
=> Remember the badges a player has between server restarts

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
? means a player that the NPC is aggressive towards is close to them, but the NPC won't attack unless the distance is reduced
! means the NPC has entered combat
Fixes #545
=> Display ? and ! above NPCs

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
=> Optimized performance by stopping AI for combat NPCs once they're dead

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java, src/main/java/com/projectswg/holocore/resources/support/global/commands/Command.java, src/main/java/com/projectswg/holocore/resources/support/global/commands/CreatureStateCheck.kt, src/main/java/com/projectswg/holocore/resources/support/global/commands/State.kt, src/main/java/com/projectswg/holocore/resources/support/global/commands/StateCheck.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Prevents being able to sit during combat, for instance.
For some reason the client doesn't display a message for these like it does for locomotions, e.g. "You cannot Melee Hit while Dead".
=> Added support for state checks on commands

src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.java
A client crash would occur before when sending a delta
=> Jedi state

src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.java
=> Added some vehicle-related system messages

src/main/java/com/projectswg/holocore/intents/gameplay/player/badge/GrantBadgeIntent.java, src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.java, src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
=> Mastering a profession now gives you a badge

src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatRegenerationService.java
=> Sitting now increases HAM regeneration by 2x

src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
=> Block loot radials while the executor is dead or incapacitated

src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
=> Don't bother displaying required combat level if it's 1

src/main/java/com/projectswg/holocore/intents/gameplay/combat/duel/DuelPlayerIntent.java, src/main/java/com/projectswg/holocore/resources/gameplay/combat/EnemyProcessor.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatDeathblowService.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/duel/DuelService.java, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java, src/main/java/com/projectswg/holocore/services/support/objects/ObjectStorageService.java, src/test/java/com/projectswg/holocore/resources/gameplay/combat/TestEnemyProcessor.kt
Fixes #380, along with other bugs I discovered after fixing 380:
1. You shouldn't enter combat immediately, that should only happen once someone attacks.
2. Defeating an opponent should let you death blow them.
3. Both players should visibly enter combat stance.
=> Fixed a couple of duel bugs

src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/DefaultWeaponFactory.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt
Also created a DefaultWeaponFactory, because the code for creating the default weapon has been copy-pasted a couple of times at this point.
The factory is now used to reduce duplication.
=> Added a couple of tests for factional PvP

serverdata/vehicles/vehicles.sdb, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/VehicleLoader.java, src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.java
=> Holocore-555 Remove buffs for players and vehicles in code

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/combat/CmdAttack.kt, src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
=> Holocore-660 Default attack

serverdata/map/map_locations.sdb
=> Fixed brawler trainers sometimes being named ";" on the map

src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
=> Grant Novice Entertainer upon character creation

src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.java
=> Entertainers get Dancing XP by dancing

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/TransferItemCallback.java, src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java, src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipInstrumentTest.kt, src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt
=> Entertainers are now granted a Slitherhorn so they can earn Musician XP

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
=> Armor Break should also affect innate armor

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ForcePowersValidWeaponChecker.kt
This allows us to implement something like Force Run.
=> Allow Force Powers to be used

src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
=> [Combat] Improper Experience Type

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
=> [Combat] Failed attacks shouldn't consume HAM

src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
=> Invulnerable faction NPCs trigger the "?"

README.md
Small issue, but had me head-scratching for a minute when I copy-pasted it a couple of days ago.
=> Fixed invalid JSON in the readme

src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/LootGenerationService.kt
=> [General] Effect on corpse

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java, src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
=> Combat_commands missing area for Force Cost and Force Cost Modifier

.idea/codeStyles/codeStyleConfig.xml, .idea/kotlinc.xml, .idea/misc.xml, .idea/vcs.xml
Mostly because git keeps picking them up. I went through them and they do seem "portable" between developers, so let's give it a shot :)
=> Added some shared IntelliJ IDEA configuration to VCS

.gitignore, README.md, docker-compose.yml, mongo_init_scripts/blue_frog.js, mongo_init_scripts/default_user.js
The idea is to simplify the setup process a bit, so it's easier to get to the point where you can develop.
=> Created a docker-compose.yml, which initializes and runs a mongo instance

src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
=> #893 bugfix: fixed escaping from enemy spams error

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
=> Added a maximum NPC distance from home of 100m

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/CmdMeditate.kt, src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/StandCmdCallback.java, src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.java, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
=> Added animation for Teras Kasi ability 'Meditate'

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
=> Damage is increased by 50% if the target is knocked down

src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java, src/main/java/com/projectswg/holocore/services/support/npc/ai/AISchedulingService.java
=> Fixed timing issue with onModeStart/End in AIObject

src/main/java/com/projectswg/holocore/resources/support/objects/ObjectCreator.java
Use of newer JDK features that didn't exist previously and Math.max
=> Fixed IDE warnings in ObjectCreator

src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java, src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.java, src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/missions/DestroyMissionListTest.kt
A NPC will simply spawn on top of you and you can get a few credits for killing it.
This should provide a foundation for the continued work with destroy missions.
=> Very basic implementation of destroy missions

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
The idea is that we can more easily propagate new settings, but primarily that IDEA uses it by default instead of the code style that JetBrains has created.
=> Added the ProjectSWG codestyle to version control

src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/generation/ItemLootGenerator.kt
=> Fixed issue where some looted items had "Volume: 0" when examining them

src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResource.java, src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResourceSpawner.kt, src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/raw/RawResourceLoader.java, src/main/java/com/projectswg/holocore/resources/gameplay/crafting/survey/SampleLoopSession.java, src/main/java/com/projectswg/holocore/resources/gameplay/crafting/survey/SurveyHandler.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt, src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/ResourceService.java, src/test/java/com/projectswg/holocore/resources/gameplay/crafting/resource/raw/TestRawResourceLoader.java
Slight refactor of the code, to avoid having GalacticResource reference ServerData
Should fix #1170 and #1169.
=> Fixed being unable to use survey tools, caused by server reboots

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt, src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
=> [Entertainer] Instruments and Props have their required skills set

src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
=> Slitherhorn has 0 volume

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/combat/FactionLoader.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.java, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionManager.kt, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionPointService.kt, src/test/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectFactionPointTest.kt
Relates to GitHub issue #675
Relevant change in pswgcommon is the addition of the `FactionResponseMessage` packet.
=> [Faction] Faction standing

src/main/java/com/projectswg/holocore/intents/gameplay/combat/CombatIntents.kt, src/main/java/com/projectswg/holocore/resources/gameplay/combat/EnemyProcessor.kt, src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdServer.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java, src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectAwareness.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatRegenerationService.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/conversation/ConversationService.java, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java, src/main/java/com/projectswg/holocore/services/support/npc/ai/AIService.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/LairAttackTest.kt
Relates to GitHub issue #1173
Manually testable with new option in /server SUI, where you can spawn a lair here and now.
Will probably be removed later, when "real" lairs are actually being spawned in the wild.
=> [Combat] Ability to damage lairs

build.gradle.kts, src/main/java/com/projectswg/holocore/resources/support/data/server_info/database/PswgBazaarInstantSalesDatabase.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgBazaarInstantSalesDatabaseMongo.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgDatabase.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java, src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.kt, src/main/java/com/projectswg/holocore/services/gameplay/commodities/BazaarService.kt, src/test/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgBazaarInstantSalesDatabaseMongoTest.kt
=> [Bazaar] Creating and viewing instant sale items

src/main/java/com/projectswg/holocore/resources/support/global/commands/SwimmingStateCheck.kt
=> [Combat] No longer possible to fight while swimming

src/main/java/com/projectswg/holocore/services/gameplay/commodities/BazaarService.kt
=> [Bazaar] Withdrawing a listed item

src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
=> [Misc] Fix being unable to set title back to No Title

src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
=> [Misc] Optimize memory usage of CombatExperienceService

.idea/runConfigurations/Start_server__development_.xml
This should make warnings/errors more obvious when developing.
=> Colored logs in development mode

src/main/java/com/projectswg/holocore/resources/support/global/commands/DrivingVehicleLocomotionCheck.kt
=> [Combat] You can no longer attack while riding a vehicle mount

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DestroyMissionLoader.kt, src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java, src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt, src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionTerminal.kt, src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionTerminalType.kt, src/main/java/com/projectswg/holocore/services/gameplay/missions/MissionListItem.kt
=> [Mission] Imperial/Rebel Mission Terminals

build.gradle.kts
Just to prevent us from falling too far behind.
=> [Misc] Updated JUnit to 5.9.3

.idea/kotlinc.xml, build.gradle.kts
No specific reason, just making sure we keep up.
Kotlin release overview: https://kotlinlang.org/docs/releases.html#release-details
=> [Misc] Updated Kotlin to 1.8.21 from 1.7.10

.idea/misc.xml, build.gradle.kts, src/main/java/com/projectswg/holocore/resources/gameplay/world/travel/TravelHelper.java, src/main/java/com/projectswg/holocore/resources/gameplay/world/travel/TravelPointContainer.java, src/test/java/com/projectswg/holocore/architecture/ArchitectureTest.kt
The rules run as a part of the suite of automated tests.
=> Added ArchUnit and configured rules for some of our current conventions, so these subtle issues can be detected without necessarily requiring a human

src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java, src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionTerminal.kt, src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/NpcDefaultAttackTest.kt
Relates to #1361.
The first commit is a refactor, to help identify what is happening.
The second commit is the actual fix, as the problem became obvious with the first commit.
=> Fixed respawning too many NPCs

src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/storage/GalacticResourceContainer.kt, src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/CreatureHarvestingService.kt, src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/ResourceService.java, src/test/java/com/projectswg/holocore/services/gameplay/crafting/resource/CreatureHarvestingTest.kt
Relates to #1372 
First commit contains a bugfix for ResourceService, second commit is the actual feature.
=> Harvesting creatures grants Scouting Experience

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
=> NPCs skip queuing commands while in water

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java, src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
=> Fixed client crashes from comm messages

src/test/java/com/projectswg/holocore/headless/CharacterSelectionScreen.kt, src/test/java/com/projectswg/holocore/headless/HeadlessSWGClient.kt, src/test/java/com/projectswg/holocore/services/support/CharacterManagementTest.kt
Simply tests that a player can delete characters that they have created and the rate limiter, for now.
=> Character management tests

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/npc/NpcStaticSpawnLoader.java, src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
=> Added new spawner flag QUEST

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdKill.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java, src/test/java/com/projectswg/holocore/headless/admin.kt, src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt
=> /kill admin command

src/test/java/com/projectswg/holocore/headless/skills.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SkillTreeTest.kt
Simply to prevent regressions of the most obvious kind.
With this in place, adding more should be trivial.
=> Some basic automated tests of skill trees

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/NpcEquipmentLoader.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/npc/NpcStaticSpawnLoader.java, src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java, src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SimpleSpawnInfo.java, src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SpawnInfo.java, src/main/java/com/projectswg/holocore/resources/support/npc/spawn/Spawner.kt, src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/NpcEquipmentLoaderTest.kt
Relates to #721
The SDB contains glasses and props, no armor like the issue describes. The glasses and props do work.
=> Load in additional NPC equipment

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java, src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
Stacktrace Undercova received:
=> [Quest] Support comm messages without a NPC

src/test/java/com/projectswg/holocore/headless/grouping.kt, src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/TipCreditsTest.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SkillTreeTest.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/group/GroupTest.kt, src/test/java/com/projectswg/holocore/services/support/CharacterManagementTest.kt, src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt, src/test/java/com/projectswg/holocore/services/support/LoginTest.kt, src/test/java/com/projectswg/holocore/test/runners/IntegrationTest.kt
Idea being that duplication can be reduced, making it easier to read and write the tests.
I also reduced the flakiness of the grouping tests by listening for a different packet.
=> Integration test superclass

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDelayAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/Die.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/RandomDie.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java, src/test/java/com/projectswg/holocore/headless/combat.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandAttack.java, src/test/java/com/projectswg/holocore/services/gameplay/player/experience/TrappingXPTest.kt, src/test/java/com/projectswg/holocore/test/runners/DeterministicDie.kt, src/test/java/com/projectswg/holocore/test/runners/IntegrationTest.kt
So we can be sure that it keeps working roughly as it should.
I performed a slight refactor to the combat engine.
The to-hit-chance was so low that having characters spamming the same attacks until a hit would finally land caused the tests to be unbearably slow at times. With the refactor, the test times became stable.
=> Testcases for Trapping XP

src/main/java/com/projectswg/holocore/resources/support/random/Die.kt, src/main/java/com/projectswg/holocore/resources/support/random/RandomDie.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/LootGenerationService.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/generation/ItemLootGenerator.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java, src/test/java/com/projectswg/holocore/headless/loot.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandAttack.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/loot/LootTest.kt, src/test/java/com/projectswg/holocore/test/runners/DeterministicDie.kt, src/test/java/com/projectswg/holocore/test/runners/IntegrationTest.kt
The test was written to confirm #1457.
=> Loot item generation test case

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
In #1464, we figured out that this TODO should just be removed.
=> Removed TODO for a NGE feature in quests

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java, src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
Fixes #1392, as no features have been left out.
=> Added support for quest.task.ground.go_to_location

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt, src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
Relates to #1492 
This one was simple enough, as it seems to want to remove the quest from the quest journal instead of completing the quest like normal.
=> quest.task.ground.clear_quest task type

docker-compose.yml
=> Upgraded mongo-express to a stable release (1.0.0)

src/main/java/com/projectswg/holocore/services/gameplay/player/group/GroupService.kt
I forgot I had this lying about. I made these changes when writing the tests for grouping, as it wasn't always easy to figure out if something was a timing issue.
=> Added logging of group events, so debugging is easier

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/PlaceStructureCmdCallback.kt
I also fixed the code formatting issues while I was in there.
=> Removed unnecessary inheritance of StartDanceCallback in PlaceStructureCmdCallback

src/main/java/com/projectswg/holocore/intents/gameplay/player/quest/QuestIntents.kt, src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/EmitQuestSignalEvent.kt, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/ConversationLoader.java, src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/EmitQuestSignalEventParser.kt, src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
We need support for signals if we want to implement the newbie quest line with Trehla Keelo, and we need to be able to emit the signals during conversations.
=> Quest signals

src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectShared.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectSharedNP.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java, src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java, src/test/java/com/projectswg/holocore/services/gameplay/combat/HealthWoundTest.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandAttack.java, src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt
Relates to #596, but doesn't close it.
We still need to apply wounds when cloning.
=> Weapons with Wound Chance apply health wounds during combat

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.kt
=> Take health wounds into account when using a healing ability

src/main/java/com/projectswg/holocore/intents/gameplay/combat/CombatIntents.kt, src/main/java/com/projectswg/holocore/resources/support/objects/swg/SWGObject.java, src/main/java/com/projectswg/holocore/services/gameplay/GameplayManager.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/DeathCyberneticService.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/cloning/CloningService.kt
=> Death cybernetics

src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.kt
I was testing something with Force Run and it only stuck around for a second or two, despite being infinite duration (-1).
=> Fixed infinite duration buffs expiring immediately

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdKill.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/cloning/CloningService.kt, src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.kt, src/test/java/com/projectswg/holocore/headless/CharacterSelectionScreen.kt, src/test/java/com/projectswg/holocore/headless/cloning.kt, src/test/java/com/projectswg/holocore/headless/combat.kt, src/test/java/com/projectswg/holocore/headless/movement.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/CloningTest.kt, src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt, src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt
=> Fixed being unable to clone

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdGoto.kt
- Added ability to teleport to spawns and patrols by ID
- Refactored code to sort through the received command
=> /Goto Improvement

src/test/java/com/projectswg/holocore/headless/CharacterSelectionScreen.kt, src/test/java/com/projectswg/holocore/headless/combat.kt, src/test/java/com/projectswg/holocore/headless/experience.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/BactaTossTest.kt
Helps us keep Bacta Toss working when completing #1714.
=> Basic automated test to verify the essential behavior of Bacta Toss

src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java, src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/HamSkillModService.kt, src/test/java/com/projectswg/holocore/headless/buffs.kt, src/test/java/com/projectswg/holocore/services/gameplay/combat/NutrientInjectionTest.kt, src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt
=> Support for healthPercent skill mod

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/TransferItemCallback.kt, src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.kt
=> Weapon hinderance
