src/main/java/com/projectswg/holocore/resources/gameplay/player/ActivePlayerPredicate.java
src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/GcwRegionLoader.java
src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgDatabase.kt
src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgGcwRegionDatabase.kt
src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/generic/CmdStopDance.java
src/main/java/com/projectswg/holocore/resources/support/objects/awareness/AwarenessType.java
src/main/java/com/projectswg/holocore/resources/support/objects/swg/guild/GuildObject.java
src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.java
src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectShared.java
src/main/java/com/projectswg/holocore/services/gameplay/gcw/CivilWarRegionService.java
src/main/java/com/projectswg/holocore/services/gameplay/gcw/GalacticCivilWarManager.java
src/main/java/com/projectswg/holocore/services/gameplay/player/PlayerManager.java
src/main/java/com/projectswg/holocore/services/gameplay/player/guild/GuildService.java
src/test/java/com/projectswg/holocore/resources/gameplay/player/TestActivePlayerPredicate.java

- Creation of regions through the sdb.
- Display regions in-game.
- Data on regions is persisted.
- Every 15 minutes presence is detected and factions are rewarded or punished for not being present.
- GCW points earned inside zones count towards percentage. Points earned outside or in space do not (yet) count.
- The GCW window isn't working 100%, but at least it doesn't crash the client anymore.

Basic GCW regions

---

src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java

Problem was that names of exotic mods don't end with _modified.
Now it just looks at anything that's under the Stat bonus or Skillmod bonus categories, which would naturally be statmods and skillmods.

Exotic mods from equipment are granted to the player when equipped

---

README.md

Also detailed that we don't need people to install Gradle anymore, just use the wrapper.

Updated readme with JDK 9 -> 13 and MongoDB instructions

---

src/main/java/com/projectswg/holocore/services/support/global/zone/CharacterLookupService.java

Problem is the CharacterLookupService in AUTHORITY is set to null when the server's shutting down.
When this happens, null pointers occur when looking up players.

Less exceptions when shutting down the server #251

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java

Implementation of #257 
Simply display `difference` in the combat log, which is also what the flytext shows.

Combat log now displays actual amount healed instead of theoretical max #257

---

src/main/java/com/projectswg/holocore/intents/gameplay/world/spawn/CreateSpawnIntent.java
src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/npc/NpcStaticSpawnLoader.java
src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdCreateNpc.java
src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SimpleSpawnInfo.java
src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SpawnInfo.java
src/main/java/com/projectswg/holocore/resources/support/npc/spawn/Spawner.kt
src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java
src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/SpawnerRadial.java
src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt

Implementation of issue #37 
NPCs can be created and destroyed.
Creation example: `/createNPC humanoid_meatlump_fool n 2`
Destruction is done by simply radialing the spawner and selecting "Destroy".
Creation allows the admin user to specify:
* Which NPC to spawn.
* Which difficulty the NPC should have: n (Normal), e (Elite) or b (Boss). If an unknown variant is entered, Normal is selected as a sane default.
* Which combat level the NPC should have.

/createNPC command #37

---

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdSetExperience.java

`/setExperience` requires a target. It's a client side thing.
`/setExperience me combat 5000` will work.
`/setExperience combat 5000` won't work. This is what the help text currently suggests is the correct form, but it's actually missing the target parameter.

The /setExperience hint now specifies that a target parameter is required

---

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt

Should fix #211. This will require creatures to use creature default weapon instead of unarmed default weapon. Undercova's making this change.

creatureMeleeAttack is now only used for the creature weapon instead of being used by every NPC #211

---

src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt

Fixes #111 
Seems getting a heading from a `Location` to another `Location` is calculated differently than from a `Location` to a `Point3D`.
This simply switches calculation methods, as the `Point3D` variant seems to do what we want.

Fixed issue where NPCs didn't face the target properly when attacking

---

src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt

Effect Name before
Effect Name after

Fixed static item weapon proc effect not displaying a proper text

---

build.gradle.kts
src/main/java/com/projectswg/holocore/services/support/npc/spawn/DynamicSpawnService.java
src/main/java/com/projectswg/holocore/utilities/TerrainUtils.java
src/main/java/module-info.java

https://github.com/madsboddum/swgterrain doesn't handle hills well enough for AI to use it just yet. Should give a *much* better experience with dynamic spawn eggs, though.
Given the issue with height detection on certain hills I don't think the issue should be closed, but this is a solid start.

Dynamic spawn eggs spawn way less frequently above or below ground #296

---

src/main/java/com/projectswg/holocore/resources/support/npc/spawn/Spawner.kt
src/main/java/com/projectswg/holocore/services/gameplay/conversation/ConversationService.java

Problem is that the spawninfos sometimes have a null conversation ID which isn't allowed by `Spawner`.
Relevant log:
```
10-01-21 03:23:12.164 T: [CommandQueueService] Ziggy/Jobut Veah executed command createnpc
10-01-21 03:23:12.166 E: Fatal Exception while processing intent: ObjectCreatedIntent
10-01-21 03:23:12.166 E: Exception in thread "intent-processor-5" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-01-21 03:23:12.166 E: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-01-21 03:23:12.166 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.invoke(Service.java:135)
10-01-21 03:23:12.166 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119) …
```

Fix error in ConversationService when spawning a NPC using /createNPC

---

serverdata/nge/command/special_lines.sdb
src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java

Included example for medic healing abilities.
Fixes #352, although the remaining healing special lines need doing as well.

Special line damage increase now applies to healing special lines as well #352

---

src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/combat/CmdPVP.java

Fixes #39
Didn't implement /setFaction, figured we could implement that if we needed it. It's possible to switch factions using the recruiters without having to wait 5 days. Eventually, /setFaction could be nice but for now it doesn't add any value.

Removed ability to change faction via /pvp command, it must now be done via the recruiters in-game #39

---

src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
src/test/java/com/projectswg/holocore/services/support/objects/radials/TestRadialService.java

Fixes #405 
Bit hard to test when nothing seems to drop valid loot, so there's a slight possibility that the radials don't do anything.

Fix loot radials appearing twice

---

serverdata/gcw/pvp_zones.sdb

Removed Restuss from the restricted PVP Zone as it's no longer required in the CU.

Removed Restuss from the restricted PVP Zone.

---

src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
src/test/java/com/projectswg/holocore/services/support/objects/radials/TestRadialService.java

Fixes #420
Previous attempt was a dud. With some tips on NPC locations from Undercova I found a testing spot and this time it actually works ;)
Code is the original one, _except_ LOOT_ALL is now parent for LOOT instead of the other way around.

Fixed double loot radial bug #420

---

serverdata/map/static_city_points.sdf
serverdata/travel/travel.sdb

Removed both Wayfar and Dathomir Quarantine Zone shuttle ports as neither exist in CU and removed the Dathomir Quarantine Zone city as this is also not present in CU.

Updates to Static Cities and Travel shuttleports

---

serverdata/vehicles/vehicles.sdb

Fixes #508
We keep the feature, but simply stop trying to apply buffs that don't exist pre-NGE.

Don't apply non-existent buffs to vehicles #508

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java
src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java

Later we need to prevent cooldowns from showing when a combat ability is executed on an invalid (or missing) target, using CommandTimerFlag.FAILED
We also need to support CommandTimerFlag.WARMUP later
Fixes #440
Fixes #445
Fixes #448
Fixes #449
Fixes #454 
Fixes #467
Fixes #471 
Fixes #474
Fixes #477

Fixed cooldowns not displaying client-side

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt

For whatever reason, a null element can sneak into the defenders Set on TangibleObject. It's a head-scratcher, as we only append the primitive long through TangibleObject#addDefender, which by definition can't be null.

Fixed sometimes being stuck in combat

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java

We had attackSpeed in the top of WEAO03, but attackSpeed isn't in there at all post-CU. This caused all variables to be off-by-one.
Fixes #621, tested locally

Fixed weapon range not being sent properly to the client

---

src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt

More specifically, it should be queued for later execution for when the relevant cooldowns have expired.
Relates to #568

Holocore-568 Global cooldown should prevent ability execution

---

src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
src/test/java/com/projectswg/holocore/services/gameplay/combat/NpcDefaultAttackTest.kt

The interesting bit is in `com.projectswg.holocore.resources.support.objects.swg.custom.AIObject#addDefaultWeapon`

Fixed a bug where NPCs couldn't attack

---

src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java

Relates to GitHub issue #730
The place the multiplier was implemented was very error-prone. Now it's been moved, so it's very difficult to mess that up in the future.

XP flytext not showing the multiplied XP correctly

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java

They're way less powerful now, making it actually possible for NPCs to hit equally-leveled players.
There's also way less difference between players with different levels now.

Tweaked how Accuracy and Defense modifiers influence combat

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java

As an example, +45 Healing Efficiency would increase the amount of damage normally healed by 45%
Relates to #919

Healing Efficiency now increases damage healed as a percentage

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/BaselineDelegate.kt

I was converting a SWGObject subclass from Java to Kotlin and I wanted to use BaselineDelegate, but Strings weren't supported.
Support is added here.

String support for BaselineDelegate

---

src/main/java/com/projectswg/holocore/ProjectSWG.java

I saw two options:
1. Closing the InputStream that was opened
2. Not opening an InputStream to begin with
I figured simply creating an `URL` would also do what we wanted, keeping the code simple.

marker.txt detection no longer opens an InputStream that's never closed

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java

Relates to GitHub issue #677
Turns out we already supported this, but the player was allowed to be more levels above the NPC than the expected 5.

[Combat] Combat and the Combat Level - lowering/increasing XP

---

src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java

Relates to GitHub issue #1267
**NOTE**: This can't _really_ happen yet, as the only way to progress in faction rank is to edit your character in MongoDB directly.
But it will be possible with #1225.

[Faction] Switching factions resets your faction rank

---

src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt
src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt
src/test/java/com/projectswg/holocore/services/gameplay/combat/NpcDefaultAttackTest.kt

Relates to GitHub issue #1275
**NOTE**: The `NPCCreator` wasn't responsible for spawning the requested amount of NPCs, so you would always have to do this yourself despite "amount" of NPCs being a thing on spawners.
This has been changed, so spawning NPCs is easier.

[Mission] Terminal missions spawn lairs

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/resource/ResourceContainerObjectShared.java

Delta nums in RCNO3 were off by 2, because variables have been removed in TANO03.
During development of #1224, I noticed that I was crashing when existing stacks of hide were increased in quantity, while new stacks was fine.
With this patch it works fine.

Fixed client crash when existing stacks of resources were adjusted

---

CONTRIBUTING.md

Fixes #1333.
The idea is to communicate why we currently have both Java and Kotlin and what should be used when.

Add section about Java and Kotlin to CONTRIBUTING.md

---

.github/dependabot.yml

Based on: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
We currently have a warning on our test runs (and probably deploy runs), because our build pipeline hasn't really been updated.
Just having them updated automatically through pull requests seemed to make sense, when it was this easy to implement.

Dependabot automatically updating GitHub Actions

---

Dockerfile

Fixes #1342
Running the Docker image unaltered, you can see the time of my Docker host not matching the Docker container.
The log lines say 15:13 (UTC), but actually it's 17:13 (GMT +2).
Being on Windows, it isn't possible to passthrough /etc/localtime as a volume mount.
This is still the default behavior, as UTC time is just the Docker default. However, we can now customize it like so:
`docker run -e TZ=Europe/Copenhagen <image>`

Docker image timezone

---

.dockerignore
.github/workflows/deploy.yml
.github/workflows/verify.yml
Dockerfile

Fixes #1351
In short:
* CI/CD pipeline now attempts to build the docker image, so we can have more confidence that it's actually working
* Running jlink now happens inside the docker image build, so it's portable
* Final Docker image size has been reduced by ~30% (240MB -> 170MB)
As for automatic updates to the base image using Dependabot, being a multi-stage build now, we appear to have lost the option to have Dependabot submit update PRs: https://github.com/dependabot/dependabot-core/issues/7640
_Technically_ we could work around it by having two Dockerfiles, as described in that issue, but I'm unsure if the added complexity is worth it at this time.
Debian Stretch has been replaced with Alpine 3.
Docker image size difference, Alpine vs. Debian:

Dockerfile overhaul

---

.idea/.name
.idea/runConfigurations/Start.xml
CONTRIBUTING.md

The idea being that you just click "Start" and everything works. Obviously you still need to consider Docker, but you also needed to do that before 😄 
The settings for the run configuration look like this:

Compound run configuration for starting docker-compose and then holocore

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.kt
src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.kt
src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/Quest.kt
src/test/java/com/projectswg/holocore/resources/gameplay/conversation/requirements/QuestSerializationTest.kt

Fixes #1383. Tested.
There were two issues:
1. The Quest struct had an extra variable that's not used pre-NGE
2. Pre-NGE doesn't have an `activeQuest` variable, and having it caused a delta offset with the `quests` map

Fixed client crash when being granted a quest #1383

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdActivateQuest.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java
src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestQuestLoader.java

Relates to #1400.
I tested the message box in-game with:
`/activateQuest quest/c_newbie_start`.
I also expanded the automated tests for QuestLoader. Turns out that a whole lot more columns needed to be optional.

Quest SUI message boxes

---

src/main/java/com/projectswg/holocore/services/support/global/zone/CharacterLookupService.java
src/main/java/com/projectswg/holocore/services/support/global/zone/LoginService.java
src/test/java/com/projectswg/holocore/headless/CharacterSelectionScreen.kt
src/test/java/com/projectswg/holocore/headless/HeadlessSWGClient.kt
src/test/java/com/projectswg/holocore/headless/MemoryUserDatabase.kt
src/test/java/com/projectswg/holocore/headless/ZonedInCharacter.kt
src/test/java/com/projectswg/holocore/headless/exceptions.kt
src/test/java/com/projectswg/holocore/headless/grouping.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/group/GroupTest.kt
src/test/java/com/projectswg/holocore/services/support/LoginTest.kt
src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java

Basically, the headless client acts as a place to store reusable test functions with an easy-to-understand API. By working at a higher level of abstraction, the testcases themselves become _very_ focused on the behavior of the game.
I like this example:
```kotlin
@Test
fun formGroup() {
val zonedInCharacter1 = createZonedInCharacter("Playerone", "Charone")
val zonedInCharacter2 = createZonedInCharacter("Playertwo", "Chartwo")
zonedInCharacter1.invitePlayerToGroup(zonedInCharacter2)
zonedInCharacter2.acceptCurrentGroupInvitation()
assertTrue(zonedInCharacter1.isInGroupWith(zonedInCharacter2))
}
```
I don't think it's the right tool for all kinds of tests, but my experience so far is that it works great for integration tests.
It would probably be a bad idea to use it to test all the …

Headless swg client

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java

I had the wrong column name, so `visible` was always `false`.
It works in-game now.

Quest journal sound

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java

Looks like this in-game:
An original Lava cannon:
I've tried to maintain the original order of the attributes.
Enables #1159

[Commando] 'Splash Damage' and 'Radius' for static item weapons

---

src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
src/test/java/com/projectswg/holocore/resources/support/objects/StaticItemCreatorTest.kt

During development of #1433, I noticed that the Lava Cannon I tested with was supposed to have some skillmods on it.
This fixes that problem.

[Items] Fixed static item weapons being created without skillmods

---

src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt

I wanted to write automated tests to cover Scouts getting Trapping XP by killing creatures, but obviously we're not making anyone a Novice Scout right out of the gate now.
Rather than adding some tech debt in the test cases by explicitly making the characters a Novice Scout, I figured re-enabling this made more sense.

Re-enable novice in all professions, so we can work on testing them

---

src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/combat/loot/LootTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/TipCreditsTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/experience/AdminCommandAccessTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SkillTreeTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/experience/TrappingXPTest.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/group/GroupTest.kt
src/test/java/com/projectswg/holocore/services/support/CharacterManagementTest.kt
src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt
src/test/java/com/projectswg/holocore/services/support/LoginTest.kt
src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt

I realized "IntegrationTest" wasn't a very accurate name for what the class is being used for.
The subclasses are actually more like acceptance tests than they are like integration tests - thus, the rename.

Renamed IntegrationTest to AcceptanceTest

---

build.gradle.kts

Warnings:
Running the jlink builds still outputs to the desired dirs. We just use the new Gradle API to declare those same locations.

Replaced two usages of a deprecated Gradle API

---

build.gradle.kts
src/test/java/com/projectswg/holocore/headless/grouping.kt
src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java

Should help with the group test failure we saw in #1467.
We were listening for deltas relating to all objects - now we're listening for deltas relating to specific objects.

Reduced flakiness of GroupTest

---

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt

Relates to #1403.
Below is the test quest `quest/test_timer`. The description and the time settings for the quest have become mismatched - ignore that. It's supposed to be 180 seconds (3 minutes).
I don't want to complete the issue though, due to a bug I just thought of. I've written a TODO where the problem is

Display quest timers

---

.github/workflows/verify.yml

Includes the change in #1447 generated by Dependabot and fixes a breaking change.
That PR should become obsolete.

Specified JDK distribution parameter, so actions/setup-java can be bumped

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt

Relates to #1460.
There's currently no way a quest can fail, so music_on_failure is loaded but not used right now.
I refactored `QuestService` a bit, because:
* ... the function name `advanceQuest` didn't really match the language used in the SDBs etc. (we don't "advance" a quest - we complete tasks)
* ... code for activating a task was duplicated - now it's in a function, where music-on-task-activation has been inserted
* ... the flow was still a bit difficult to understand with `handleTaskEvents`, where it relied on some state being modified beforehand

[Quest] Play music on quest task activation and completion

---

build.gradle.kts

After the recent upgrade of Gradle to 8.5, Gradle has begun warning us of deprecated behavior when running automated tests.
Here's an example snippet:
```
> Task :test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
BUILD SUCCESSFUL in 3s
12 actionable tasks: 3 executed, 9 up-to-date
18:10:48: Execution finished ':test --tests …
```

Improved Gradle 9.x compatibility

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ExplorationBadgeLoader.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt
src/test/java/com/projectswg/holocore/headless/badges.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeTest.kt
src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt

Fixes #1455
I added teleportation handling in `ExplorationBadgeService`, so our tests wouldn't have to actually move the character around with data transforms. I tried going down the movement route, but it was quite complex and didn't really seem worth it after a couple of hours.
I figured this wouldn't hurt to have during real gameplay either.
The added test failed before fixing the problems in `ExplorationBadgeLoader` and passed after.

Fixed exploration badges

---

src/test/java/com/projectswg/holocore/architecture/production/ProductionArchitectureTest.kt
src/test/java/com/projectswg/holocore/architecture/testing/AcceptanceTestRules.kt
src/test/java/com/projectswg/holocore/architecture/testing/JUnitRules.kt
src/test/java/com/projectswg/holocore/architecture/testing/TestingArchitectureTest.kt

We have some rules for production code already - this PR introduces a few more, but for the tests of production code.
There are some (unwritten) best practices when it comes to writing tests. I've tried capturing the ones I could think of in ArchRules, so keeping things neat is easier.
All our existing code passes with flying colors (phew... 😅), so I didn't actually have to edit anything.
But for that reason, I had to write some code that broke the rules - using JUnit 3, JUnit 4, instantiating packets and referencing intents in a subclass of `AcceptanceTest`. I've obviously not included that here, but the point is that I've seen the tests both pass and fail when they should.

ArchUnit rules for testcases

---

build.gradle.kts

Patches this minor vulnerability in Holocore: CVE-2023-42503.
Testcontainers depends on Apache Commons Compress and new releases have been made of both libraries that patch the problem.
I discovered it because IntelliJ IDEA has a Checkmarx integration these days that alerted me when I was randomly browsing the build script.
Maybe there's something we can run periodically to help discover this kind of issue? 🤔

Patch CVE-2023-42503 (minor security vulnerability)

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/MemoryRetrievedItemRepository.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestRetrieveItemRadialHandler.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/RetrievedItemRepository.kt

Relates to #1398.
Contains a refactor of `QuestLoader`. The class was horrible to work in with the amount of code lines needed to load just 1 column.
It's a little better now, but I have a TODO on converting it to Kotlin and continuing with the refactor effort.
I was facing annoying problems with the behavior where all columns were being loaded for all types of tasks. Most of the time, all columns don't have (meaningful) data in them and that made the parsing logic explode very often. It's more robust now for a couple of task types, but more task types need to be converted to this approach in the near future.

quest.task.ground.retrieve_item

---

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt

Fixes #1493
Basically, the code was checking if more tasks were coming.
It didn't account for existing tasks possibly not being complete yet.

Fixed issue where quests with multiple active tasks at once would complete prematurely

---

build.gradle.kts

Patches minor vulnerability CVE-2021-20328.
I've been through the release notes of the mongodb driver and the only thing I've found that affects the codebase is the fact that java.util.logging has been replaced with SLF4J.
For that reason I had to twiddle with the SLF4J dependency a bit. It's no longer just for the Testcontainers library during testing, it's now also for the mongodb driver.
We have this bit of code in `PswgDatabase`:
```kotlin
private fun setupMongoLogging() {
var mongoLogger: Logger? = Logger.getLogger("com.mongodb")
while (mongoLogger != null) {
for (handler in mongoLogger.handlers) {
mongoLogger.removeHandler(handler)
}
if (mongoLogger.parent != null)
mongoLogger = mongoLogger.parent
else
break
}
mongoLogger?.addHandler(object : Handler() {
override fun publish(record: …
```

Bumped mongodb driver in order to patch CVE-2021-20328

---

src/test/java/com/projectswg/holocore/headless/HeadlessSWGClient.kt

It *currently* doesn't mean anything in terms of exceptions. Holocore just logs "null" sometimes.
Here's a snippet of what the log looks like in acceptance tests now:
```
22-12-23 17:23:53.631 D: [LoginService] Playerone logged in from localhost
22-12-23 17:23:53.631 T: [CharacterCreationService] Playerone created player at spawn location tat_moseisley
22-12-23 17:23:53.632 D: [CharacterCreationService] Playerone created character 'Charone' from localhost
22-12-23 17:23:53.633 D: [ZoneService] Playerone/Charone connected to zone server from localhost
```

Headless client now sets an actual SocketAddress

---

.idea/inspectionProfiles/Project_Default.xml

The idea is to make formatting errors easier to find - like using spaces instead of tabs.
This is the specific setting I tweaked in the inspections profile:
Example in the IDE:
After applying the suggested 'Fix':
Without this change, the same block of code shows no visual warnings to the developer:

Tweaked the default inspection profile so that it shows a "weak warning" whenever the Code Style isn't being followed

---

.idea/codeStyles/Project.xml

I've been noticing that lines were being wrapped pretty aggressively. You can actaully see an example of it at line 178-180 below.
I recently enabled visual "helper lines" in IDEA for whitespaces and method separation, which made the problem very obvious.
Before this change:
After this change, where the wrapping point is so far away that it can't be seen:

Fixed short "Hard Wrap" for Kotlin and Java in the Code Style

---

src/test/java/com/projectswg/holocore/headless/grouping.kt
src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java

Stumbled across this little gem a while back. The exceptions are instantiated but never actually thrown.
Throwing them revealed some issues with waiting for the packets.

Fixed grouping test DSL not throwing exceptions

---

build.gradle.kts

Seeing which tests failed is good, but also seeing why they failed is even better.
With this change, the exception stacktrace is also printed. Useful for assertion failures, null pointer exceptions etc.

Show exception stacktraces in case of test failure

---

src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.kt

In a nutshell: Having `EntertainmentService` check for the presence of "Novice Entertainer" when players use `/startDance` etc. is unnecessary, because `CommandService` already does that. You can only use commands that you have been given - at least these days.
I also fixed some code formatting violations while I was in there.

Removed unnecessary isEntertainer-check in EntertainmentService

---

src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java

This has been bothering me for a while. That one method is _way_ too long.
Most of the cell loaders that look similar have been extracted into dedicated methods, so the return value can be fed directly into the setter on the `QuestTaskInfo` object.
IMO there are more issues with this class, but I figured I'd start here.

Simplify loading of tasks in QuestLoader

---

src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt

We don't have support for something like quest.task.ground.craft, because holocore has no crafting subsystem at this time.
The newbie quest line contains a crafting element, but getting stuck there would be unfortunate.
Therefore, this new logic simply skips the task types holocore doesn't yet support.

Skip unsupported quest task types and let the player know what happened

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.kt
src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.kt

More code cherry-picked from #1341. The changes relate to #589.
Draft schematics are now granted, but the "Slot Data" and "Attribute Data" requests receive no response yet.

Grant draft schematics from skills

---

.github/dependabot.yml

Sometimes trivial changes are made in pswgcommon, such as: ProjectSWGCore/pswgcommon@4dfa51e7f479eba4b48e1058e3326ca078f3d8aa
Due to it being trivial, I didn't bother with creating a PR for the updated version in holocore.
It's a bit bad, because the next time changes are made in pswgcommon, they may not be trivial.
In that case, the PR now contains the complex changes *and* old, trivial ones.
Assuming this is merged, we should see a PR created by Dependabot to update the pswgcommon git submodule to the revision mentioned above.

Automatically create PRs for updating pswgcommon to the latest version

---

src/main/java/com/projectswg/holocore/services/gameplay/newbie/NewbieService.kt

I had to get a bit creative with the two intent handlers.
At the time `CreatedCharacterIntent` is emitted, the owner of the `CreatureObject` is `null`, because the client hasn't requested zone-in yet.
And when the character is being zoned in, we don't have access the character creation context.
For that reason, the `recentlyCreatedCharacters` field contains some short-lived state, as the client triggers the zone-in flow right after character creation.

Hand out the newbie quest to newly created characters

---

src/main/java/com/projectswg/holocore/intents/gameplay/player/quest/QuestIntents.kt
src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestRetrieveItemRadialHandler.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt

This required a bigger refactor than I had anticipated, honestly.
Problem was that I needed access to `QuestListInfo#category` way down in `completeQuest`, but all I had was a string `questName`. I do think this improves the code by introducing some type safety, though.
In-game now, using the test quest "quest/test_grant_quest_complete" bundled with SWG:
From an original screenshot:

Added missing system message when completing a quest

---

src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectShared.kt
src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java

* Server loads up fine with existing characters, thanks to `MongoData#getArray` returning an empty list.
* I removed some old DB migration code regarding base3 that has served its purpose.
* I introduced some new DB migration code to ensure old creatures have a valid initial state regarding wounds.

Persist wounds, so a server reboot won't reset them

---

src/main/java/com/projectswg/holocore/services/support/global/chat/ChatInstantMessageService.java
src/test/java/com/projectswg/holocore/headless/CharacterSelectionScreen.kt
src/test/java/com/projectswg/holocore/headless/ignorelist.kt
src/test/java/com/projectswg/holocore/headless/tells.kt
src/test/java/com/projectswg/holocore/services/support/global/chat/TellTest.kt
src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt

This covers all behaviors that I've been able to find regarding tells. With this, we can safely rewrite the whole subsystem - a conversion to Kotlin, for example.
The packets that the testing DSL "send" don't have the `packetType` field inside set. That field is only set when deserializing the packet in the networking code. There's no other way to set them.
I edited `ChatInstantMessageService` a bit for that reason, as `Objects.requireNonNull(packet.getPacketType()) == PacketType.CHAT_INSTANT_MESSAGE_TO_CHARACTER` always evaluated to `false`.
Perhaps something can be done regarding the statefulness of `SWGPacket` - that's a problem for another day, though.
An idea that sprung to mind was simply setting the fields inside the packet constructors - a `ChatInstantMessageToCharacter` packet …

Automated tests for tells

---

src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.kt

Fixes #458
Fixes #851
Fixes #1130
Animations and action costs are already in place for Aim and the enhanced variants.
The missing piece was simply the skillmod applied by the buff not being used.

Combat engine now takes accuracy bonus from buffs into account

---

src/test/java/com/projectswg/holocore/services/gameplay/combat/CloningTest.kt
src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt

Fixes the compilation errors on `master`.
https://github.com/ProjectSWGCore/Holocore/actions/runs/9754473170/job/26921422514

Testcase compilation error fixes

---

src/main/java/com/projectswg/holocore/resources/support/global/zone/sui/SuiMessageBox.kt
src/main/java/com/projectswg/holocore/services/support/global/zone/LoginService.java
src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java
src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt

Fixes #1568.
I was able to reproduce the problem with our existing automated tests by simply introducing packet encoding and decoding in this commit: b7139af3de1d0f31c79f615dbc1bfcfe3b133ecb
The result isn't used for anything, although I think that would be cool to add in later for tests that give even more confidence.
The actual fix is here: b7139af3de1d0f31c79f615dbc1bfcfe3b133ecb

Fixed a NullPointerException when displaying SUI message boxes

---

src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/HamSkillModService.kt
src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/HealthPercentCalculator.kt
src/test/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/HealthPercentCalculatorTest.kt

As was discussed in Discord, for the most part.
I decided to move the handling of the skill mod inside `CreatureObject`. My reasons:
1. Potential race condition between `SkillModService` and `HamSkillModService`. `HamSkillModService` now needs to know how much healthPercent the `CreatureObject` already has, but this information may or may not have been altered in the meantime by `SkillModService`.
2. This way, the healthPercent mod will also work if you call `CreatureObject#adjustSkillmod` directly.
1: Initial state, no buffs or anything
2: With Nutrient Injection (healthPercent +10%)
3: Nutrient Injection expired

Fixed buggy behaviors with healthPercent

---

src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.kt

Fixes #1289
Apparently the client completely stops applying customization variables after encountering ones that it doesn't recognize.
Simply removing the ones it doesn't know resolves the issue.
I figured out which to remove by having a look in customizatio/customization_id_manager.iff:
Works now:
It's worth noting that this has affected much more than jetpack hover height - only max speed was ever _actually_ being applied by the client. The jetpack hover height was just very obvious.

Fixed most vehicle customization variables not being applied

---

src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java
src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/CreatureObjectRadial.kt

Added missing radial option for watching a dancer
